import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from 'next'

import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}
import "./globals.css";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "next-themes";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    
      <html
        lang="en"
        
        suppressHydrationWarning
      >
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
          <header className="flex flex-col">
            <Navbar />
          </header>
          <main>
            
              {/* Navbar Component */}

              {children}
           
          </main>
          </ThemeProvider>
        </body>
      </html>
     
    </ClerkProvider>
  );
}
